version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/proyecto

file_exists_behavior: OVERWRITE

hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 100
      runas: ubuntu
      overwrite: true

  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 100
      runas: ubuntu
      overwrite: true

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 100
      runas: ubuntu
      overwrite: true
      